version: "3.4"

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80 --log.level=DEBUG
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  chamelogator:
    dns:
      - 8.8.8.8
    image: chamelogator
    volumes:
      # - type: volume
      #   source: /home/ryi58813/Documents/ChameleonProject/dbs/
      #   target: /data/dbs
      #   read_only: true
      #   volumes:
      #     nocopy: false
      - chameleon-db:/appuser/
      - /home/ryi58813/Documents/ChameleonProject/dbs/:/appuser/dbs/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    labels:
      - traefik.enable=true
      - traefik.backend=flask
      - traefik.flask.port=5000

volumes:
 chameleon-db:
    driver: local
